# Practice problem generated by Google Gemini aligned with concepts of flow control in Chapter 2. 

# The Challenge: The Autonomous Lab Sorter
# Write a program that helps a robotic arm decide what to do with a chemical sample based on its temperature and pH level.

# The Logic Requirements:
    # First, ask the user for the temperature (as an integer) and the pH level (as a float).
    # Safety First: If the temperature is above 100, immediately print: "DANGER: Temperature too high. Activating cooling system."
    # Acid Check: If the temperature is 100 or below, AND the pH is less than 7.0, print: "Sample is acidic. Moving to Acid Station."
    # Base Check: If the temperature is 100 or below, AND the pH is greater than 7.0, print: "Sample is basic. Moving to Base Station."
    # Neutral/Stable Check: If the temperature is 100 or below AND the pH is exactly 7.0, print: "Sample is neutral. Moving to long-term storage."

temperature = input('What is the sample temperature?')
temperature = int(temperature)

pH_level = input('What is the sample pH level?')
pH_level = float(pH_level)

if temperature > 100:
    print("DANGER: Temperature too high. Activating cooling system.")
elif temperature <= 100 and pH_level < 7.0:
    print("Sample is acidic. Moving to Acid Station.")
elif temperature <= 100 and pH_level > 7.0:
    print("Sample is basic. Moving to Base Station.")
elif temperature <= 100 and pH_level == 7.0:
    print("Sample is neutral. Moving to long-term storage.")
else:
    print("Please re-read the instructions and try again.")