# Example problem generated by Google Gemini to test concepts aligned with Chapter 3 of "Automate the Boring Stuff with Python"

current_temp = 40 # initializes Transformer temp variable
load_percent = 50 # initializes load percentage variable

while current_temp < 100:
    print('LOAD: ' + str(load_percent) + '% | TEMP: ' + str(current_temp) + ' degrees C')
    load_percent += 5 # Progressively increases testing load percentage while loop evaluates to TRUE. 
    current_temp += (load_percent * 0.1) # Progressively increases current temp in line with increasing load percentage. 
    if load_percent >= 150: #adds safety break for excessive load. 
        break

print('Simulation ended. Final Temp: ' + str(current_temp) + ' degrees C.')